# Generated by Django 6.0.3 on 2026-04-11 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_imagen_noticia_subtitulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='bio',
        ),
    ]
